version: "3"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: burek
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"

  php:
    build:
      context: ./docker/php
    volumes:
      - "./html:/var/www/html"

  web:
    build:
      context: ./docker/web
    depends_on:
      - db
      - php
    ports:
      - "80:80"
    volumes:
      - "./html:/var/www/html:ro"

volumes:
  db_data: