<?php

function grunfes_menu() {
  $items = [];

  $items['my_picks/%'] = [
    'title' => t('My Picks Page'),
    'page arguments' => [1],
    'page callback' => 'grunfes_pick_pool',
    'access arguments' => ['access content'],
  ];

  $items['publish_picks'] = [
    'title' => t('Publish picks'),
    'page arguments',
    [1],
    'page callback' => 'grunfes_publish_pick',
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function grunfes_form_pool_node_form_alter(&$form, &$form_state, $form_id) {
  if (
    isset($form['field_matches_to_pick']['und']['#options']) &&
    count($form['field_matches_to_pick']['und']['#options']) > 0
  ) {
    $options = array_keys($form['field_matches_to_pick']['und']['#options']);
    $form['field_matches_to_pick']['und']['#default_value'] = $options;
    $form['field_matches_to_pick']['und']['#attributes'] = array('checked' => 'checked');
  };
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function grunfes_form_match_node_form_alter(&$form, &$form_state, $form_id) {

  // Hide the start date.
  // Start date get's updated through rules.
  $form['field_start_date']['#access'] = TRUE;
}

/**
 * Implements hook_views_pre_view().
 */
function grunfes_views_pre_view(&$view, &$display_id, &$args) {
  /** @var \view $view */
  if ($view->name == 'view_matches_by_company' && $view->current_display == 'entityreference_1') {
    $tids = isset($_POST['field_company'])
      ? implode('+', $_POST['field_company']['und'])
      : '';

    $view->set_arguments([
      'tids' => $tids,
    ]);
  }
}

function grunfes_update_match_date($updated_show, $match_to_update) {
  $show_entity = entity_metadata_wrapper('node', $updated_show);
  $match_entity = entity_metadata_wrapper('node', $match_to_update);
  $match_entity->field_start_date->set($show_entity->field_start_date->value());
  $match_entity->save();
}

/**
 * Check if user is administrator.
 *
 * @return boolean
 */
function is_user_administrator() {
  global $user;
  return in_array('administrator', $user->roles);
}

function grunfes_is_new_pick($user_id, $pool_id) {
  $user_picks = grunfes_get_user_picks_by_pool($user_id, $pool_id);

  return count($user_picks) === 0;
}

function grunfes_get_user_picks_by_pool($user_id, $pool_id) {
  $query = db_select('node', 'n')
    ->condition('n.type', 'user_pick')
    ->condition('n.uid', $user_id)
    ->condition('fpid.field_pool_id_value', $pool_id);
  $query->addField('n', 'nid');

  $query->innerJoin('field_data_field_pool_id', 'fpid', 'n.nid = fpid.entity_id');

  return array_keys($query->execute()->fetchAllAssoc('nid'));
}

function grunfes_pick_pool($pool_id) {
  global $user;

  $post_data = $_POST;

  if (!isset($post_data['redirectUrl'])) {
    drupal_goto('/');
  }

  $results = grunfes_get_user_picks_by_pool($user->uid, $pool_id);
  $is_new_pick = count($results) === 0;

  if (!og_is_member('node', $pool_id)) {
    drupal_set_message(
      t('Please subscribe to current pool to place your picks.'),
      'error'
    );
    drupal_goto($_POST['redirectUrl']);
  }

  $user_entity = entity_metadata_wrapper('user', $user);
  $pool_node = node_load($pool_id);

  $count = 0;

  foreach ($post_data as $key => $value) {
    if (strpos($key, 'match') === FALSE) {
      continue;
    }

    $match_id = explode('_', $key)[1];

    if ($is_new_pick) {
      $pick = entity_create('node', [
        'type' => 'user_pick',
      ]);

      $pick_entity = entity_metadata_wrapper('node', $pick);
      $pick_entity->title = $user->name . '-' . $pool_node->title . '-' . $match_id;
      $pick_entity->author = $user->uid;
      $pick_entity->field_pool_id = $pool_id;
      $pick_entity->field_match_id = $match_id;
      $pick_entity->field_team_picked = $value;
      $pick_entity->save();

      $user_entity->field_picks[] = $pick_entity->nid->value();
    }
    else {
      $pick = node_load($results[$count]);
      $pick_entity = entity_metadata_wrapper('node', $pick);
      $pick_entity->field_team_picked = $value;
      $pick_entity->save();
    }

    $count++;
  }

  if ($is_new_pick) {
    $user_entity->save();
  }

  drupal_set_message(t('Your picks has been saved'));
  drupal_goto($_POST['redirectUrl']);

  return [];
}

function grunfes_publish_pick($pool_id) {
  if (!is_user_administrator()) {
    drupal_goto('/');
  }

  $pool = node_load($pool_id);

  if ($pool === NULL) {
    drupal_goto('/');
  }

  $redirect_url = isset($_POST['redirectUrl'])
    ? $_POST['redirectUrl']
    : '/';

  $pool_closed = empty($pool->field_closed['und'][0]['value'])
    ? FALSE
    : $pool->field_closed['und'][0]['value'];

  if ($pool_closed) {
    drupal_set_message('Picks already published.');
    drupal_goto($redirect_url);
  }

  $pool_entity = entity_metadata_wrapper('node', $pool);
  $pool_entity->field_closed = TRUE;

  $admin_picks = grunfes_get_user_picks_by_pool(1, $pool_id);
  $pool_users = $pool_entity->members->value();

  foreach ($pool_users as $pool_user) {
    if (in_array('administrator', $pool_user->roles)) {
      continue;
    }

    $user_picks = grunfes_get_user_picks_by_pool($pool_user->uid, $pool_id);
    $user_points = grunfes_calculate_pick_points($admin_picks, $user_picks);

    $score = entity_create('leaderboard_score', [
      'type' => 'leaderboard_score',
    ]);

    $score_entity = entity_metadata_wrapper('leaderboard_score', $score);

    $d = _wrapper_debug($score_entity);

    $score_entity->field_user = $pool_user->uid;
    $score_entity->field_score = $user_points;
    $score_entity->field_pool_id = $pool_id;

    $score_entity->save();

    drupal_set_message("User {$pool_user->name} earned {$user_points} points.");
  }

  $pool_entity->save();

  drupal_set_message('Picks published.');
  drupal_goto($redirect_url);
}

function grunfes_calculate_pick_points($admin_picks, $user_picks) {
  if (count($user_picks) === 0) {
    return 0;
  }

  $points = 0;
  $all_hits = TRUE;

  foreach ($admin_picks as $index => $value) {
    $admin_pick = node_load($value);
    $user_pick = node_load($user_picks[$index]);

    if ($user_pick === NULL) {
      $all_hits = FALSE;
      $points = 0;
      break;
    }

    $match = node_load($admin_pick->field_match_id['und'][0]['value']);
    $points_to_earn = intval($match->field_point_to_earn['und'][0]['value']);

    if (
      isset($admin_pick->field_team_picked['und'][0]['safe_value']) &&
      isset($user_pick->field_team_picked['und'][0]['safe_value'])
    ) {
      if (
        $admin_pick->field_team_picked['und'][0]['safe_value'] ==
        $user_pick->field_team_picked['und'][0]['safe_value']
      ) {
        $points += $points_to_earn;
      }
      else {
        $all_hits = FALSE;
      }
    }
  }

  if ($all_hits) {
    $points += 50;
  }

  return $points;
}

function grunfes_reset_pool($admin_picks, $user_picks) {
  if (count($user_picks) === 0) {
    return 0;
  }

  $points = 0;
  $all_hits = TRUE;

  foreach ($admin_picks as $index => $value) {
    $admin_pick = node_load($value);
    $user_pick = node_load($user_picks[$index]);

    $all_hits = FALSE;
    $points = 0;
    break;
    }

    
  return $points;
}

function grunfes_fetch_pick($user_id, $pool_id, $match_id) {
  $query = db_select('node', 'n')
    ->condition('n.uid', $user_id)
    ->condition('fpid.field_pool_id_value', $pool_id)
    ->condition('mid.field_match_id_value', $match_id);
  $query->addField('tid', 'field_team_picked_value');
  $query->innerJoin('field_data_field_pool_id', 'fpid', 'n.nid = fpid.entity_id');
  $query->innerJoin('field_data_field_match_id', 'mid', 'n.nid = mid.entity_id');
  $query->innerJoin('field_revision_field_team_picked', 'tid', 'n.nid = tid.entity_id');

  $results = $query->execute()->fetchAssoc();

  return !isset($results['field_team_picked_value'])
    ? FALSE : $results['field_team_picked_value'];
}

function grunfes_render_matches($pool_id, $fields) {
  global $user;
  
  $team_keys = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];
  $html = '';

  $match_id = $fields['field_team_a']->raw;
  $results = grunfes_fetch_pick($user->uid, $pool_id, $match_id);

  $match_entity = entity_metadata_wrapper('node', $match_id);
  $match_timestamp = intval($match_entity->field_start_date->value());
  $match_close_timestamp = $match_timestamp - 60 * 60 * 2;
  $now = new DateObject();
  $date_expired = $now->getTimestamp() >= $match_close_timestamp;

  if ($date_expired) {
    $_SESSION['show_expired'] = TRUE;
  }

  foreach ($team_keys as $index => $value) {
    if (isset($fields["field_team_{$value}"]->content)) {
      $team = $fields["field_team_{$value}"];
      $is_checked = $results === $team->content;

      $is_disabled = $date_expired || $pool_id === FALSE || !og_is_member('node', $pool_id);

      if (is_user_administrator()) {
        $is_disabled = FALSE;
      }

      if ($results === FALSE && $index === 0) {
        $is_checked = TRUE;
      }

      $html .= grunfes_render_match($team, $is_checked, $is_disabled);
    }
  }

  return $html;
}

function grunfes_render_match($field_team, $is_checked, $is_disabled) {
  $match_id = $field_team->raw;

  $tpl = '<div class="left p5">{{input}}{{name}}</div>';

  $disabled = $is_disabled
    ? 'disabled'
    : '';

  $checked = $is_checked
    ? 'checked'
    : '';

  $input = "<input
    class=\"user-pick user-pick-input\"
    type=\"radio\"
    {$disabled}
    {$checked}
    name=\"match_{$match_id}\"
    value=\"{$field_team->content}\" />";

  return str_replace([
    '{{input}}',
    '{{name}}',
  ], [
    $input,
    $field_team->content,
  ], $tpl);
}

function grunfes_default_rules_configuration_alter(&$data) {
  $directory_iterator = new \DirectoryIterator(realpath(__DIR__ . '/rules'));

  foreach ($directory_iterator as $file_info) {
    if ($file_info->isFile() && $file_info->isReadable()) {
      $rulename = 'rules_' . pathinfo($file_info->getFilename(), PATHINFO_FILENAME);

      if (!isset($data[$rulename])) {
        $rule = file_get_contents($file_info->getPathname());
        $data[$rulename] = entity_import('rules_config', $rule);
      }
    }
  }
}

function grunfes_update_matches(&$node) {
  // $node_wrapper = entity_metadata_wrapper('node', $node);
  // $matches = [];

  // foreach($node_wrapper->field_matches_to_pick->getIterator() as $show) {
  //   foreach ($show->field_matches->getIterator() as $match) {
  //     $matches[] = array(
  //       'target_id' => $match->nid->value(),
  //     );
  //   }
  // }

  // $node_wrapper->field_matches_to_pick->set($matches);
  // $node->field_matches_to_pick['und'] = $matches;
  // node_save($node);


  // $node_wrapper->save();
}

function grunfes_entity_presave($entity, $type) {
  if ($type === 'node' && $entity->type === 'pool') {
    $node_wrapper = entity_metadata_wrapper('node', $entity);
    $matches = [];

    foreach($node_wrapper->field_matches_to_pick->getIterator() as $show) {
      foreach ($show->field_matches->getIterator() as $match) {
        $matches[] = array(
          'target_id' => $match->nid->value(),
        );
      }
    }
    $entity->field_matches_to_pick['und'] = $matches;
    dsm($entity);
  }
}

// function _wrapper_debug($w) {
//   $values = [];
//   foreach ($w->getPropertyInfo() as $key => $val) {
//     $values[$key] = $w->$key->value();
//   }
//   return $values;
// }
